"""
Generate docs/admin/config.yml for Sveltia CMS.

Run from the repo root:  python tools/build-cms-config.py

Why a generator: Sveltia has no nested collections, so every leaf folder under
docs/ needs its own collection, and Sveltia drops any frontmatter field that
isn't declared. Hand-maintaining ~30 near-identical blocks is how fields go
missing. Edit the tables below, re-run, commit both files.

Rules baked in (see comments in the output file):
  - Cadwallon bodies are raw-Markdown only (rich text rewrites wikilinks/callouts).
  - Slugs keep Title Case and spaces so [[Wikilinks]] resolve.
  - Everything is `required: false` except the hidden constants, so half-filled
    pages still save.
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "admin" / "config.yml"

HEADER = """\
# Sveltia CMS configuration — https://randolin.github.io/IronCircle/admin/
# GENERATED by tools/build-cms-config.py — edit that script, not this file.
#
# Edit pages in the browser; Save = a commit to `main`, which triggers the normal
# Pages deploy. Sign-in is GitHub OAuth; you need write access to the repo.
#
# Things to know:
#   - Sveltia only saves fields declared here. Anything else in a page's
#     frontmatter is DROPPED on save. New field in a folder -> add it to the script.
#   - No nested collections yet, so every leaf folder is its own collection.
#     New folder -> add it to the script.
#   - Cadwallon bodies are edited in raw Markdown only: the rich-text editor
#     rewrites wikilinks, callouts and Dataview blocks.
#   - Slugs keep Title Case and spaces so [[Wikilinks]] keep resolving.
#     Apostrophes are stripped from NEW file names ("S'ylice" -> "S ylice").
#   - backend.base_url is the OAuth relay (sveltia-cms-auth on Cloudflare
#     Workers). Replace the placeholder after deploying it.
"""


def s(name, label, hint=None, **kw):
    f = {"label": label, "name": name, "widget": "string", "required": False}
    if hint:
        f["hint"] = hint
    f.update(kw)
    return f


def lst(name, label):
    return {"label": label, "name": name, "widget": "list", "required": False}


def num(name, label, **kw):
    f = {"label": label, "name": name, "widget": "number", "value_type": "int", "required": False}
    f.update(kw)
    return f


def hidden(name, default):
    return {"name": name, "widget": "hidden", "default": default}


def body(rich=False):
    return {
        "label": "Body",
        "name": "body",
        "widget": "markdown",
        "modes": ["raw", "rich_text"] if rich else ["raw"],
        "required": False,
    }


# --- Cadwallon universal fields (00 Reference/Schema.md) ---------------------
CAD_UNIVERSAL = [
    s("title", "Title (new pages only)",
      "Becomes the file name. Leave blank when editing an existing page."),
    s("exposure", "Exposure", "public | rumored | secret — secret is GM-only and never published"),
    s("canon", "Canon", "core | homebrew"),
    s("completeness", "Completeness", "stub | draft | complete"),
    s("status", "Status", "In-world condition, where the type has one"),
    lst("aliases", "Aliases"),
    lst("tags", "Tags"),
]

WORLD = [
    s("type", "Type", "nation | place | concept | deity | moc"),
    *CAD_UNIVERSAL,
    s("alliance", "Alliance", "Ways of Light | Meanders of Darkness | Paths of Destiny | neutral | none"),
    s("culture", "Culture (totem)"),
    s("race", "Race"),
    s("embassy", "Embassy", "[[District]] or none"),
    s("region", "Region"),
    s("controlled-by", "Controlled by"),
    s("domain", "Domain (deity)"),
]

CITY = [
    s("type", "Type", "place | district | fief | concept | moc"),
    *CAD_UNIVERSAL,
    s("fief", "Fief", "[[Fief]]"),
    s("tier", "Tier", "lower | upper"),
    s("attitude", "Attitude"),
    s("ruling-house", "Ruling house"),
    s("peer", "Peer", "[[Character]]"),
    s("motto", "Motto"),
    s("ducal-enclave", "Ducal enclave"),
    s("region", "Region"),
    s("controlled-by", "Controlled by"),
]

CULTURE = [
    s("type", "Type", "culture | people | moc"),
    *CAD_UNIVERSAL,
    s("origin", "Origin", "native | immigrant | created | ancient"),
    s("size", "Size", "small | medium | large"),
    s("alliance", "Alliance"),
]

FACTION = [
    s("type", "Type", "faction | guild | organization | location | moc"),
    *CAD_UNIVERSAL,
    s("faction-type", "Faction type", "guild | free-league | house | militia | order | network"),
    s("hq", "HQ", "[[District]]"),
    s("sphere", "Sphere"),
    s("leader", "Leader", "[[Character]]"),
    s("faction", "Parent faction"),
    s("founded", "Founded"),
]

PEOPLE = [
    s("type", "Type", "character | moc", default="character"),
    *CAD_UNIVERSAL,
    s("faction", "Faction", "[[Faction]]"),
    s("location", "Location", "[[Fief]] / [[District]] / [[Site]] — one link"),
    s("ancestry", "Ancestry", "[[Culture]]"),
    s("role", "Role"),
    s("age", "Age"),
    s("source", "Source"),
]

HISTORY = [
    s("type", "Type", "history | timeline | moc"),
    *CAD_UNIVERSAL,
    num("date", "Date (year AF)"),
    s("era", "Era", "elder | lost-city | free-city"),
]

COSMOLOGY = [
    s("type", "Type", "concept | deity | item | moc"),
    *CAD_UNIVERSAL,
    s("alliance", "Alliance"),
    s("domain", "Domain (deity)"),
]

UNDERGROUND = [
    s("type", "Type", "site | location | moc"),
    *CAD_UNIVERSAL,
    s("layer", "Layer", "surface | shallow | deep | labyrinth"),
    s("access", "Access", "[[District]] or [[Place]]"),
    s("source", "Source"),
]

CAMPAIGN = [
    s("type", "Type", "moc | thread | session"),
    *CAD_UNIVERSAL,
    s("stakes", "Stakes"),
    lst("related", "Related"),
    s("date", "Date", "YYYY-MM-DD for sessions"),
    num("session-number", "Session number"),
    lst("present", "Present"),
]

PCS = [
    hidden("type", "pc"),
    *CAD_UNIVERSAL,
    s("player", "Player"),
    s("pronouns", "Pronouns"),
    s("ancestry", "Ancestry", "[[Culture]]; two links for mixed ancestry"),
    s("community", "Community"),
    s("community-archetype", "Community archetype"),
    s("class", "Class"),
    s("subclass", "Subclass"),
    lst("domains", "Domains"),
    num("level", "Level", min=1, max=10),
    s("transformation", "Transformation"),
    s("image", "Image", "[[Portrait.png]]"),
]

REFERENCE = [s("type", "Type", "reference | moc"), *CAD_UNIVERSAL]


def folder(name, label, path, fields, icon, create=True, rich=False, **kw):
    c = {
        "name": name,
        "label": label,
        "icon": icon,
        "folder": path,
        "create": create,
        "summary": "{{filename}}",
        "fields": [*fields, body(rich)],
    }
    c.update(kw)
    return c


# --- Stillwater Rise ----------------------------------------------------------
SW_GM_FIELDS = [
    {"label": "Title", "name": "title", "widget": "string"},
    hidden("exposure", "secret"),
    hidden("campaign", "Stillwater Rise"),
]


def sw_file(name, label, file, extra=None):
    return {
        "name": name,
        "label": label,
        "file": f"docs/stillwater-rise/gm/{file}",
        "fields": [*SW_GM_FIELDS, *(extra or []), body()],
    }


DISTRICT_FIEFS = [
    ("den-azhir", "Den Azhir"), ("drakaer", "Drakaër"), ("gamehead", "Gamehead"),
    ("ghieronburg", "Ghieronburg"), ("kraken", "Kraken"), ("ogrokh", "Ogrokh"),
    ("soma", "Soma"), ("automaton", "The Automaton"), ("rampart", "The Rampart"),
    ("trophy", "Trophy"), ("var-nokkt", "Var-Nokkt"),
]

DIVIDER = {"divider": True}

collections = [
    {
        "name": "root",
        "label": "Site",
        "icon": "home",
        "files": [
            {"name": "home", "label": "Landing page", "file": "docs/index.md",
             "fields": [s("title", "Title"), body(rich=True)]},
            {"name": "documentation", "label": "Documentation index", "file": "docs/Documentation/index.md",
             "fields": [s("title", "Title"), body(rich=True)]},
        ],
    },
    DIVIDER,
    {
        "name": "sw-public",
        "label": "Stillwater Rise — Players",
        "icon": "visibility",
        "files": [
            {"name": "index", "label": "Case file (public)", "file": "docs/stillwater-rise/index.md",
             "fields": [{"label": "Title", "name": "title", "widget": "string"},
                        hidden("exposure", "public"), body(rich=True)]},
        ],
    },
    {
        "name": "sw-gm",
        "label": "Stillwater Rise — GM",
        "icon": "visibility_off",
        "files": [
            sw_file("hub", "GM Hub + CURRENT STATE", "index.md"),
            sw_file("campaign", "Campaign doc", "campaign.md",
                    [s("status", "Status", "placeholder | draft | reconciled")]),
            sw_file("danger-board", "Danger board", "danger-board.md"),
            sw_file("decisions", "Decisions log", "decisions.md"),
            sw_file("themes", "Character themes (Suno)", "themes.md"),
            sw_file("roster-index", "Roster — index & prompt conventions", "roster/index.md"),
            sw_file("roster-victim", "Roster — the victim", "roster/victim.md"),
            sw_file("roster-tier-a", "Roster — Tier A (the board)", "roster/tier-a.md"),
            sw_file("roster-tier-b", "Roster — Tier B (working surface)", "roster/tier-b.md"),
            sw_file("roster-tier-c", "Roster — Tier C (the world)", "roster/tier-c.md"),
            sw_file("roster-agency", "Roster — the agency", "roster/agency.md"),
        ],
    },
    {
        "name": "sw-sessions",
        "label": "Stillwater Rise — Sessions (GM)",
        "icon": "event_note",
        "folder": "docs/stillwater-rise/gm/sessions",
        "create": True,
        "slug": "{{title}}",
        "summary": "{{filename}} — {{status}}",
        "sortable_fields": ["session-number", "date"],
        "fields": [
            {"label": "File name", "name": "title", "widget": "string",
             "hint": "Use session-NN, e.g. session-02. Also the page title."},
            hidden("exposure", "secret"),
            hidden("campaign", "Stillwater Rise"),
            num("session-number", "Session number"),
            s("date", "Date played", "YYYY-MM-DD, blank until played"),
            {"label": "Status", "name": "status", "widget": "select",
             "options": ["planning", "played"], "default": "planning"},
            body(rich=True),
        ],
    },
    DIVIDER,
    {
        "name": "ff-setting",
        "label": "Fate Foretold — Setting",
        "icon": "auto_stories",
        "files": [
            {"name": "kalystra", "label": "Kalystra Setting", "file": "docs/Fate Foretold/Kalystra Setting.md",
             "fields": [body()]},
            {"name": "pantheon", "label": "Pantheon", "file": "docs/Fate Foretold/Pantheon.md",
             "fields": [body()]},
        ],
    },
    {
        "name": "ff-characters",
        "label": "Fate Foretold — Characters",
        "icon": "person",
        "folder": "docs/Fate Foretold/Characters",
        "create": True,
        "identifier_field": "name",
        "summary": "{{filename}}",
        "fields": [
            hidden("type", "npc"),
            {"label": "Name", "name": "name", "widget": "string"},
            lst("aliases", "Aliases"),
            s("status", "Status"),
            s("role", "Role"),
            s("location", "Location", "[[Wikilink]]"),
            s("faction", "Faction", "[[Wikilink]]"),
            body(),
        ],
    },
    DIVIDER,
    folder("cad-reference", "Cadwallon — 00 Reference", "docs/Cadwallon/00 Reference", REFERENCE, "menu_book", create=False),
    folder("cad-world", "Cadwallon — 01 World", "docs/Cadwallon/01 World", WORLD, "public"),
    folder("cad-nations", "Cadwallon — 01 World / Nations", "docs/Cadwallon/01 World/Nations", WORLD, "flag"),
    folder("cad-city", "Cadwallon — 02 City", "docs/Cadwallon/02 City", CITY, "location_city"),
    folder("cad-fiefs", "Cadwallon — 02 City / Fiefs", "docs/Cadwallon/02 City/Fiefs", CITY, "castle"),
    *[
        folder(f"cad-districts-{slug}", f"Districts / {label}",
               f"docs/Cadwallon/02 City/Districts/{label}", CITY, "holiday_village")
        for slug, label in DISTRICT_FIEFS
    ],
    folder("cad-cultures", "Cadwallon — 03 Cultures", "docs/Cadwallon/03 Cultures", CULTURE, "groups"),
    folder("cad-cultures-homebrew", "Cadwallon — 03 Cultures / Homebrew", "docs/Cadwallon/03 Cultures/Homebrew", CULTURE, "groups"),
    folder("cad-factions", "Cadwallon — 04 Factions", "docs/Cadwallon/04 Factions", FACTION, "diversity_3"),
    folder("cad-free-leagues", "Factions / Free Leagues", "docs/Cadwallon/04 Factions/Free Leagues", FACTION, "diversity_3"),
    folder("cad-guilds", "Factions / Guilds", "docs/Cadwallon/04 Factions/Guilds", FACTION, "diversity_3"),
    folder("cad-other-orgs", "Factions / Other Organizations", "docs/Cadwallon/04 Factions/Other Organizations", FACTION, "diversity_3"),
    folder("cad-people", "Cadwallon — 05 People", "docs/Cadwallon/05 People", PEOPLE, "person",
           sortable_fields=["faction", "location", "status"]),
    folder("cad-history", "Cadwallon — 06 History", "docs/Cadwallon/06 History", HISTORY, "history_edu",
           sortable_fields=["date"]),
    folder("cad-cosmology", "Cadwallon — 07 Cosmology & Magic", "docs/Cadwallon/07 Cosmology & Magic", COSMOLOGY, "auto_awesome"),
    folder("cad-underground", "Cadwallon — 08 Underground", "docs/Cadwallon/08 Underground", UNDERGROUND, "stairs"),
    folder("cad-campaign", "Cadwallon — 09 Campaign", "docs/Cadwallon/09 Campaign", CAMPAIGN, "casino"),
    folder("cad-pcs", "Cadwallon — 09 Campaign / Characters (PCs)", "docs/Cadwallon/09 Campaign/Characters", PCS, "badge",
           summary="{{filename}} ({{player}})"),
]

config = {
    "backend": {
        "name": "github",
        "repo": "Randolin/IronCircle",
        "branch": "main",
        "base_url": "https://REPLACE-ME.workers.dev",
    },
    "site_url": "https://randolin.github.io/IronCircle/",
    "display_url": "https://randolin.github.io/IronCircle/",
    "media_folder": "/docs/assets/uploads",
    "public_folder": "/assets/uploads",
    "slug": {
        "encoding": "unicode",
        "clean_accents": False,
        "sanitize_replacement": " ",
        "lowercase": False,
    },
    "output": {
        "omit_empty_optional_fields": True,
        "yaml": {"quote": "none"},
    },
    "collections": collections,
}

if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    class Dumper(yaml.SafeDumper):
        def ignore_aliases(self, data):  # expand shared field lists instead of &anchors
            return True

    text = yaml.dump(config, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=200)
    OUT.write_text(HEADER + "\n" + text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(collections)} collection entries")
